# Generated by Django 6.0.4 on 2026-10-07 06:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def copy_event_prices(apps, schema_editor):
    """Existing bookings predate price snapshots; use their event's current price."""
    Booking = apps.get_model('events', 'Booking')
    for booking in Booking.objects.select_related('event'):
        booking.unit_price = booking.event.price
        booking.save(update_fields=['unit_price'])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_booking_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.RunPython(copy_event_prices, migrations.RunPython.noop),
    ]
